LOCAL_PATH := vendor/explay/porcupine
PRODUCT_COPY_FILES += \
$(LOCAL_PATH)/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/hwcomposer.mt8389.so:system/lib/hw/hwcomposer.mt8389.so \
$(LOCAL_PATH)/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)/proprietary/lib/egl/libEGL_mtk.so:system/lib/egl/libEGL_mtk.so \
$(LOCAL_PATH)/proprietary/lib/egl/libEGL.so:system/lib/egl/libEGL.so \
$(LOCAL_PATH)/proprietary/lib/egl/libGLESv1_CM.so:system/lib/egl/libGLESv1_CM.so \
$(LOCAL_PATH)/proprietary/lib/egl/libGLESv2.so:system/lib/egl/libGLESv2.so \
$(LOCAL_PATH)/proprietary/lib/libGLES_android.so:system/lib/libGLES_android.so \
$(LOCAL_PATH)/proprietary/lib/libEGL.so:system/lib/libEGL.so \
$(LOCAL_PATH)/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
$(LOCAL_PATH)/proprietary/lib/libion.so:system/lib/libion.so \
$(LOCAL_PATH)/proprietary/etc/vold.fstab:system/etc/vold.fstab \
$(LOCAL_PATH)/proprietary/usr/idc/hid-keyboard.idc:system/usr/idc/hid-keyboard.idc \
$(LOCAL_PATH)/proprietary/usr/keylayout/hid-keyboard.kl:system/usr/keylayout/hid-keyboard.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
$(LOCAL_PATH)/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
$(LOCAL_PATH)/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
$(LOCAL_PATH)/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
$(LOCAL_PATH)/proprietary/etc/wifi/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
$(LOCAL_PATH)/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
$(LOCAL_PATH)/proprietary/lib/libril.so:system/lib/libril.so \
$(LOCAL_PATH)/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
$(LOCAL_PATH)/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
$(LOCAL_PATH)/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
$(LOCAL_PATH)/proprietary/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
$(LOCAL_PATH)/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
$(LOCAL_PATH)/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
$(LOCAL_PATH)/proprietary/bin/rild:system/bin/rild \
$(LOCAL_PATH)/proprietary/bin/rildmd2:system/bin/rildmd2 \
$(LOCAL_PATH)/proprietary/bin/test_rild_porting:system/bin/test_rild_porting \
$(LOCAL_PATH)/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
$(LOCAL_PATH)/proprietary/etc/agps_profiles_conf.xml:system/etc/agps_profiles_conf.xml \
$(LOCAL_PATH)/proprietary/etc/android.hardware.location.gps.xml:system/etc/android.hardware.location.gps.xml \
$(LOCAL_PATH)/proprietary/bin/akmd8963:system/bin/akmd8963 \
$(LOCAL_PATH)/proprietary/bin/akmd8975:system/bin/akmd8975 \
$(LOCAL_PATH)/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
$(LOCAL_PATH)/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAacDec.so:system/lib/libMtkOmxAacDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAacEnc.so:system/lib/libMtkOmxAacEnc.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAmrEnc.so:system/lib/libMtkOmxAmrEnc.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAMRNBDec.so:system/lib/libMtkOmxAMRNBDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAMRWBDec.so:system/lib/libMtkOmxAMRWBDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxAwbEnc.so:system/lib/libMtkOmxAwbEnc.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxVorbisDec.so:system/lib/libMtkOmxVorbisDec.so \
$(LOCAL_PATH)/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
$(LOCAL_PATH)/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
$(LOCAL_PATH)/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so
